# This is a basic workflow to help you get started with Actions

name: CI

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Electron Builder Action
        uses: samuelmeuli/action-electron-builder@v1.4.0
        with:
          # GitHub authentication token
          github_token: ${{ secrets.github_token }}
          # Whether the app should be released after a successful build
          release: ${{ startsWith(github.ref, 'refs/tags/app-v') }}
          # Directory where NPM/Yarn commands should be run
          package_root: shells/electron
          app_root: shells/electron
