name: Embed Build

on:
  push:
    branch:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    needs:
      - maven-deps
    steps:
      - uses: actions/checkout@v1

      - name: Cache maven
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: m2-${{ hashFiles('deps.edn') }}
          restore-keys: |
            m2-

      - uses: DeLaGuardo/setup-clj-kondo@master
        with:
          version: '2021.03.31'

      - uses: DeLaGuardo/setup-clojure@master
        with:
          tools-deps: '1.10.1.469'

      - name: Setup Babashka
        uses: turtlequeue/setup-babashka@master
        with:
          babashka-version: 0.3.5

      - name: Lint
        run: bb lint

  maven-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Cache maven
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: m2-${{ hashFiles('deps.edn') }}
          restore-keys: |
            m2-

      - uses: DeLaGuardo/setup-clojure@master
        with:
          tools-deps: '1.10.1.469'

      - name: Load deps
        run: clojure -Stree

  npm-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            node_modules-

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: NPM Install
        run: npm install

  build-embed:
    runs-on: ubuntu-latest
    needs:
      - lint
      - maven-deps
      - npm-deps
    steps:
      - uses: actions/checkout@v1

      - name: Cache maven
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: m2-${{ hashFiles('deps.edn') }}
          restore-keys: |
            m2-

      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            node_modules-

      - uses: DeLaGuardo/setup-clojure@master
        with:
          tools-deps: '1.10.1.469'

      - name: Setup Babashka
        uses: turtlequeue/setup-babashka@master
        with:
          babashka-version: 0.3.5

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Compile Embed
        run: bb embed:js-release

      - name: Compile Embed CSS
        run: bb embed:css-release

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./shells/embed
