# This is a basic workflow to help you get started with Actions

name: Build/release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.2
        with:
          # Install just one or all simultaneously
          cli: 1.10.1.693 # Clojure CLI based on tools.deps

      - name: Setup Babashka
        uses: turtlequeue/setup-babashka@master
        with:
          babashka-version: 0.4.0

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: NPM Install
        run: npm install

      - name: Build CSS
        run: bb app:css-release

      - name: Build JS
        if: ${{ matrix.os != 'windows-latest' }}
        run: bb app:js-release

      - name: Build JS on Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: bb app:js-release
        shell: powershell

      - name: Electron Builder Action
        uses: samuelmeuli/action-electron-builder@v1.6.0
        with:
          # GitHub authentication token
          github_token: ${{ secrets.github_token }}
          # Whether the app should be released after a successful build
          release: true
          # Directory where NPM/Yarn commands should be run
          package_root: shells/electron
          app_root: shells/electron
          skip_build: true
